### ISSUE TITLE
Cannot find module 'hello-lib'

### ISSUE THREAD

**Issue by weiwei** [jrr/typescript-workspaces-example#1]
Although the steps passed following the README, I get the following message in VSCode:

```
Cannot find module 'hello-lib' or its corresponding type declarations.ts(2307)
```

<img width="542" alt="image" src="https://user-images.githubusercontent.com/31764/181185107-723f5a7e-c44a-4aef-a9bd-b2da4470748a.png">

A fix would be nice.

**Comment by jrr** [comment]
@weiwei Thanks for the report! I was able to reproduce the problem, and (I believe) fix it. Can you pull the latest from `main` and try again?

**Comment by weiwei** [comment]
@jrr It does work! I think yours is a great example of minimum starting point. Thanks for the update!
